windowrule = float on, match:title ^(BenX-Compact)$
windowrule = size 400 500, match:title ^(BenX-Compact)$
windowrule = move onscreen 100%-w-20 80, match:title ^(BenX-Compact)$
windowrule = pin on, match:title ^(BenX-Compact)$

windowrule = float on, match:title ^(BenX-Notification)$
windowrule = size 150 40, match:title ^(BenX-Notification)$
windowrule = move onscreen 100%-w-20 20, match:title ^(BenX-Notification)$
windowrule = pin on, match:title ^(BenX-Notification)$
